### PR TITLE
Removing reversed from base_individual_class.html

### PR DESCRIPTION
**Pull request by afs2015**
Currently classes are being shown in the reverse chronological order [as shown here on Cat's Corner's Website](https://registration.catscorner.ca/classes/2019/February/swing-2/). 

Boston Lindy Hop, had the same previous issue until we overwrote the template in our custom repo. This pull request is to fix the issue in Django Dance School.

### CODE REVIEW

**Comment by afs2015** [comment]
@riclima: Once this is live the issue should be fixed for Cat's Corner as well but if you want a stop-gap fix override the template base_indivdual_class.html and remove `reversed` in `{% for class in series.eventoccurrence_set.all %}`.

**Comment by afs2015** [comment]
New Columbia Swing has this issue as well [as shown here](https://newcolumbiaswing.org/classes/2019/January/swing-1-intro-lindy-hop/).

**Comment by afs2015** [comment]
Tried removing the newline and it caused a similar behavior to https://github.com/django-danceschool/django-danceschool/pull/121 where it made the Files changed much more difficult to read for a code review. I'm proposing we ignore the EOF convention for now and fix it for the project as a whole once we agree upon a project wide convention.

**Comment by riclima** [comment]
For the time being, the correct thing to do is to use the file’s current line ending, so that patches show correctly. The problem is probably not on Vim (unless you explicitly changed the newline setting on it) but likely on the git configuration, as it may change the newlines before commit/checkout according to how you configured it.

**Comment by riclima** [comment]
You mean LF endings? CR only are no longer in popular usage I believe. I can make the pull request if you point the commit you’d like to rebase it from.

**Comment by leetucker** [comment]
@riclima  Right, sorry, LF endings.

I've got some other things under active development that will go into the next major release (0.9.0), which involve modifications across several modules, and for which changes aren't committed in the repo yet.  So, unless the CRLF endings are causing problems for people, I would suggest that we do the swap after those changes are committed, hopefully within a week or two depending on my schedule.

**Comment by riclima** [comment]
Yeah this is really low priority. Any modern editor should be able to transparently edit both line endings.

**Pull request merged**
