### PR TITLE
Simplify README text

### PR DESCRIPTION
**Pull request by ADubhlaoich**
I think a lot of the README text was quite overly verbose and had a lot
of redundant information and unnecessary qualifiers. The tone and
perspective also changed quite a lot.

I pretty much stripped down everything I could and tried to re-phrase
everything where it made sense. I think the README itself could still go
with a lot more work, but I will propose it as part of a larger set of
changes alongside a pull request.

### CODE REVIEW

**Comment by afs2015** [comment]
@leetucker This looks okay to me, i'm fine to have this merged in.

**Comment by afs2015** [comment]
@leetucker: Is it okay if I merge this in or are there any changes you would like?

**Comment by leetucker** [comment]
Hi @ADubhlaoich , sorry I haven't had the opportunity to look at this yet.  I should be able to look at it in the next week or so though, I will let you know as soon as I am able.

**Comment by leetucker** [comment]
OK, all looks good.  Thanks for this!

**Pull request merged**
